In [86]:
import time
import numpy as np

In [87]:
list = np.random.random(100000000)

In [88]:
start_time = time.time()
print("Average using list functions = ", sum(list) / len(list))
print("Time took = ", time.time() - start_time)

Average using list functions =  0.500003755471463
Time took =  13.897486448287964


In [89]:
start_time = time.time()
print("Average using NumPy = ", np.mean(list))
print("Time took = ", time.time() - start_time)

Average using NumPy =  0.500003755471316
Time took =  0.1758878231048584


In [90]:
x = np.array([1, 2, 3, 4, 5])
print()
print("x = ", x)
print()

print("Shape = ", x.shape)
print("Type = ", type(x))
print("dType = ", x.dtype)


x =  [1 2 3 4 5]

Shape =  (5,)
Type =  <class 'numpy.ndarray'>
dType =  int32


In [91]:
s = np.array(["Yogesh", "Walia"])
print()
print("s = ", s)
print()

print("Shape = ", s.shape)
print("Type = ", type(s))
print("dType = ", s.dtype)


s =  ['Yogesh' 'Walia']

Shape =  (2,)
Type =  <class 'numpy.ndarray'>
dType =  <U6


In [92]:
m = np.array([1, 2,"Yogesh", "Walia"])
print()
print("m = ", m)
print()

print("Shape = ", m.shape)
print("Type = ", type(m))
print("dType = ", m.dtype)


m =  ['1' '2' 'Yogesh' 'Walia']

Shape =  (4,)
Type =  <class 'numpy.ndarray'>
dType =  <U11


In [93]:
m = np.array([[1, 2], [3, 4], [5, 6]])
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1 2]
 [3 4]
 [5 6]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  int32


In [94]:
m = np.array([[1.0, 2.2], [3.1, 4.0], [5.1, 6.2]])
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1.  2.2]
 [3.1 4. ]
 [5.1 6.2]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  float64


In [95]:
m = np.array([[1, 2], [3, 4.2], [5, 6]])
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1.  2. ]
 [3.  4.2]
 [5.  6. ]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  float64


In [96]:
m = np.array([[1, 2], [3, 4.4], [5, 6]], dtype=np.int64)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1 2]
 [3 4]
 [5 6]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  int64


In [97]:
n = np.array([[1, 2], [3, 4.4], [5, 6]])

np.save('float_array', n)
m = np.load('float_array.npy')

print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1.  2. ]
 [3.  4.4]
 [5.  6. ]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  float64


In [98]:
m = np.zeros((2,3))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[0. 0. 0.]
 [0. 0. 0.]]

Shape =  (2, 3)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  float64


In [99]:
m = np.ones((2,3))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1. 1. 1.]
 [1. 1. 1.]]

Shape =  (2, 3)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  float64


In [100]:
m = np.full((2,3), 4)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[4 4 4]
 [4 4 4]]

Shape =  (2, 3)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  int32


In [101]:
m = np.eye(3)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Shape =  (3, 3)
Size =  9
Type =  <class 'numpy.ndarray'>
dType =  float64


In [102]:
m = np.diag([3, 5, 3])
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[3 0 0]
 [0 5 0]
 [0 0 3]]

Shape =  (3, 3)
Size =  9
Type =  <class 'numpy.ndarray'>
dType =  int32


In [103]:
m = np.arange(3)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[0 1 2]

Shape =  (3,)
Size =  3
Type =  <class 'numpy.ndarray'>
dType =  int32


In [104]:
m = np.arange(3, 10)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[3 4 5 6 7 8 9]

Shape =  (7,)
Size =  7
Type =  <class 'numpy.ndarray'>
dType =  int32


In [105]:
m = np.arange(3, 10, 2)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[3 5 7 9]

Shape =  (4,)
Size =  4
Type =  <class 'numpy.ndarray'>
dType =  int32


In [106]:
m = np.linspace(3, 10, 3)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[ 3.   6.5 10. ]

Shape =  (3,)
Size =  3
Type =  <class 'numpy.ndarray'>
dType =  float64


In [107]:
m = np.linspace(3, 15, 2, endpoint=False)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[3. 9.]

Shape =  (2,)
Size =  2
Type =  <class 'numpy.ndarray'>
dType =  float64


In [108]:
x = np.arange(9)
print()
print(x)
print()

print("Shape = ", x.shape)
print("Size = ", x.size)
print("Type = ", type(x))
print("dType = ", x.dtype)

m = np.reshape(x, (3, 3))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[0 1 2 3 4 5 6 7 8]

Shape =  (9,)
Size =  9
Type =  <class 'numpy.ndarray'>
dType =  int32

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape =  (3, 3)
Size =  9
Type =  <class 'numpy.ndarray'>
dType =  int32


In [109]:
m = np.arange(9).reshape(3, 3)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape =  (3, 3)
Size =  9
Type =  <class 'numpy.ndarray'>
dType =  int32


In [110]:
m = np.linspace(2, 10, 5).reshape(5, 1)
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]]

Shape =  (5, 1)
Size =  5
Type =  <class 'numpy.ndarray'>
dType =  float64


In [111]:
m = np.random.random((2, 2))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[0.49384639 0.77291046]
 [0.75521978 0.34563228]]

Shape =  (2, 2)
Size =  4
Type =  <class 'numpy.ndarray'>
dType =  float64


In [112]:
m = np.random.randint(3, 6, size = (3, 2))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)


[[4 5]
 [4 4]
 [5 4]]

Shape =  (3, 2)
Size =  6
Type =  <class 'numpy.ndarray'>
dType =  int32


In [113]:
m = np.random.normal(5, 2, size = (100, 100))
print()
print(m)
print()

print("Shape = ", m.shape)
print("Size = ", m.size)
print("Type = ", type(m))
print("dType = ", m.dtype)
print("max = ", m.max())
print("min = ", m.min())
print("mean = ", m.mean())
print("+ve count = ", (m > 0).sum())
print("-ve count = ", (m < 0).sum())


[[4.278727   3.11294054 7.97477482 ... 8.10283277 4.57595918 7.1538537 ]
 [6.55110393 6.50183159 2.9400153  ... 2.4796136  2.74610033 5.78970576]
 [3.7257301  2.92014692 7.29882946 ... 4.68484092 5.77829552 5.49807265]
 ...
 [1.36132959 7.45068603 7.87498426 ... 1.30516544 3.79190933 6.87590169]
 [9.71742689 7.35811414 5.78760305 ... 5.87912824 4.51789596 7.47352834]
 [2.00073673 4.77174494 1.70035395 ... 4.25211383 4.52464448 5.00345107]]

Shape =  (100, 100)
Size =  10000
Type =  <class 'numpy.ndarray'>
dType =  float64
max =  12.7801609545809
min =  -2.999349870417107
mean =  4.990115175386582
+ve count =  9939
-ve count =  61


In [114]:
m = np.array([2,5,3,1])
print()
print(m)
print()

print("1st Element = ", m[0])
print("3rd Element = ", m[2])
print("Last Element = ", m[-1])
print("Second Last Element = ", m[-2])


[2 5 3 1]

1st Element =  2
3rd Element =  3
Last Element =  1
Second Last Element =  3


In [115]:
m = np.array([[2,5,3,1] , [1,4,5,6]])
print()
print(m)
print()

print("Original 3rd Element = ", m[0, 2])

m[0, 2]=5

print("Modified 3rd Element = ", m[0, 2])

print()
print(m)
print()


[[2 5 3 1]
 [1 4 5 6]]

Original 3rd Element =  3
Modified 3rd Element =  5

[[2 5 5 1]
 [1 4 5 6]]



In [116]:
x=np.array([1,4,6,3,2])

print()
print(x)
print()

x=np.delete(x, [1, 3])

print("Deleting 2nd and 4th Element...")

print()
print(x)
print()


[1 4 6 3 2]

Deleting 2nd and 4th Element...

[1 6 2]



In [117]:
x=np.array([[1,4,2], [4,6,2]])

print()
print(x)
print()

y=np.delete(x, 0, axis=0)
z=np.delete(x, [1, 2], axis=1)

print("Deleting 1st Row...")

print()
print(y)
print()

print("Deleting 2nd and 3rd Columns...")

print()
print(z)
print()


[[1 4 2]
 [4 6 2]]

Deleting 1st Row...

[[4 6 2]]

Deleting 2nd and 3rd Columns...

[[1]
 [4]]



In [118]:
x=np.array([1,4,4,6,2])
y=np.array([[1,4,2], [4,6,2]])

print()
print(x)
print()

x1=np.append(x, [4,6])

print()
print(x1)
print()

print()
print(y)
print()

y1=np.append(y, [[1, 2, 3], [3, 4, 5]], axis=0)

print("Appending Row(s)...")

print()
print(y1)
print()

z=np.append(y, [[1, 4], [4, 8]], axis=1)

print("Appending Column(s)...")

print()
print(z)
print()


[1 4 4 6 2]


[1 4 4 6 2 4 6]


[[1 4 2]
 [4 6 2]]

Appending Row(s)...

[[1 4 2]
 [4 6 2]
 [1 2 3]
 [3 4 5]]

Appending Column(s)...

[[1 4 2 1 4]
 [4 6 2 4 8]]



In [119]:
x=np.array([1,4,5,6,7])
y=np.array([[1,4,2], [4,6,2]])

print()
print(x)
print()

x1=np.insert(x, 1, [2,3])

print()
print(x1)
print()

print()
print(y)
print()

y1=np.insert(y, 1, [[1, 2, 3], [3, 4, 5]], axis=0)

print("Inserting Row(s)...")

print()
print(y1)
print()

z=np.insert(y, 1, [[6, 8], [3, 4]], axis=1)

print("Inserting Column(s)...")

print()
print(z)
print()


[1 4 5 6 7]


[1 2 3 4 5 6 7]


[[1 4 2]
 [4 6 2]]

Inserting Row(s)...

[[1 4 2]
 [1 2 3]
 [3 4 5]
 [4 6 2]]

Inserting Column(s)...

[[1 6 3 4 2]
 [4 8 4 6 2]]



In [120]:
x=np.array([1,2])
y=np.array([[1,4], [4,6]])

print()
print(x)
print()

print()
print(y)
print()

x1=np.vstack((x, y))

print("Stacking X on Top of Y....")

print()
print(x1)
print()

y1=np.hstack((y, x.reshape(2, 1)))

print("Stacking X on Right of Y..Reshape Needed...")

print()
print(y1)
print()


[1 2]


[[1 4]
 [4 6]]

Stacking X on Top of Y....

[[1 2]
 [1 4]
 [4 6]]

Stacking X on Right of Y..Reshape Needed...

[[1 4 1]
 [4 6 2]]



In [121]:
x=np.array([1, 2, 4, 5])
y=np.arange(20).reshape(4, 5)

print()
print(x)
print()

x1=x[2:]

print()
print(x1)
print()

print()
print(y)
print()

y1=y[1:,2:]
print()
print(y1)
print()

y2=y[2,:]
print()
print(y2)
print()

y3=y[:,3]
print()
print(y3)
print("Shape = ", y3.shape)
print()

y4=y[:,3:4]
print()
print(y4)
print("Shape = ", y4.shape)
print()


[1 2 4 5]


[4 5]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


[10 11 12 13 14]


[ 3  8 13 18]
Shape =  (4,)


[[ 3]
 [ 8]
 [13]
 [18]]
Shape =  (4, 1)



In [122]:
y=np.arange(20).reshape(4, 5)

print()
print(y)
print()

y1=y[1:,2:]

print()
print(y1)
print()

y1[1, 2] = 20

print()
print(y1)
print()

print()
print(y)
print()



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


[[ 7  8  9]
 [12 13 20]
 [17 18 19]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 20]
 [15 16 17 18 19]]



In [123]:
y=np.arange(20).reshape(4, 5)

print()
print(y)
print()

y1=y[1:,2:].copy()
#y1=np.copy(y[1:, 2:])

print()
print(y1)
print()

y1[1, 2] = 20

print()
print(y1)
print()

print()
print(y)
print()


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


[[ 7  8  9]
 [12 13 20]
 [17 18 19]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [124]:
x=np.arange(20).reshape(4, 5)

indices=np.array([1, 3])

print()
print(x)
print()

print()
print(indices)
print()

x1=x[indices, :]

print("\n",x1, "\n")

x2=x[:, indices]

print("\n",x2, "\n")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[1 3]


 [[ 5  6  7  8  9]
 [15 16 17 18 19]] 


 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]] 



In [125]:
x=np.arange(1, 10).reshape(3, 3)

print()
print(x)
print()

print("\n main diag = ", np.diag(x))
print("\n left of main diag = ", np.diag(x, k=-1))
print("\n right of main diag = ", np.diag(x, k=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


 main diag =  [1 5 9]

 left of main diag =  [4 8]

 right of main diag =  [2 6]


In [126]:
y=np.array([[1,4], [4,6], [2,6]])

print(y)

print("\n unique elements = ", np.unique(y))

[[1 4]
 [4 6]
 [2 6]]

 unique elements =  [1 2 4 6]


In [135]:
y=np.arange(100).reshape(5, 20)

print(y)

print("\n y > 25 \n", y[y > 25])
print("\n y < 25 \n", y[y < 25])
print("\n y == 25 \n", y[y == 25])

y[(y < 25) & (y > 10)]=-1

print("\n y = \n",y)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]

 y > 25 
 [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]

 y < 25 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 y == 25 
 [25]

 y = 
 [[ 0  1  2  3  4  5  6  7  8  9 10 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [138]:
y=np.arange(10)
x=np.arange(12)

print(y)
print(x)

print("Common = \n", np.intersect1d(y, x))
print("In y but not in x = \n", np.setdiff1d(y, x))
print("All = \n", np.union1d(y, x))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Common = 
 [0 1 2 3 4 5 6 7 8 9]
In y but not in x = 
 []
All = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [147]:
x=np.random.randint(1, 5, size=(10,))

print(x)

print("\nSorting (out of place) = \n", np.sort(x))

print("\n", x, "\n")

print("\nSorting (in-place) = ")

x.sort()
print(x)

[3 3 4 4 1 3 2 2 3 1]

Sorting (out of place) = 
 [1 1 2 2 3 3 3 3 4 4]

 [3 3 4 4 1 3 2 2 3 1] 


Sorting (in-place) = 
[1 1 2 2 3 3 3 3 4 4]


In [153]:
x=np.random.randint(1, 12, size=(4,4))
print(x)

print("\nSorting (in-place) = ")

print("\n Sorting by rows (axis=1)")

x.sort(axis=1)

print(x)

print("\n Sorting by columns (axis=0)")

x.sort(axis=0)

print(x)

[[11  9  8 10]
 [ 2  5  3  7]
 [ 9  3  1  4]
 [ 3  1  1  8]]

Sorting (in-place) = 

 Sorting by rows (axis=1)
[[ 8  9 10 11]
 [ 2  3  5  7]
 [ 1  3  4  9]
 [ 1  1  3  8]]

 Sorting by columns (axis=0)
[[ 1  1  3  7]
 [ 1  3  4  8]
 [ 2  3  5  9]
 [ 8  9 10 11]]


In [155]:
x=np.array([1, 2, 3, 4])
y=np.array([5, 6, 7, 8])

print(x)
print(y)

print(x+y)
print(np.add(x, y))

print(x-y)
print(np.subtract(x, y))

print(x*y)
print(np.multiply(x, y))

print(x/y)
print(np.divide(x, y))

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [156]:
x=np.array([1, 2, 3, 4]).reshape(2, 2)
y=np.array([5, 6, 7, 8]).reshape(2, 2)

print(x)
print(y)

print(x+y)
print(np.add(x, y))

print(x-y)
print(np.subtract(x, y))

print(x*y)
print(np.multiply(x, y))

print(x/y)
print(np.divide(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [157]:
x=np.array([1, 2, 3, 4]).reshape(2, 2)
y=np.array([5, 6, 7, 8]).reshape(2, 2)

print(x)
print(y)

print(np.exp(x))
print(np.sqrt(x))
print(np.power(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[    1    64]
 [ 2187 65536]]


In [158]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [159]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [160]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
